### PR TITLE
Comment out useless vfunc inside of usercmd.h

### PR DESCRIPTION
**Pull request by matty45**
This virtual function breaks struct alignment and is not used.

### CODE REVIEW

**Comment by matty45** [comment]
no idea what happened here, only changed one file

**Comment by danielga** [comment]
I force-pushed changes to the x86-64 branch, to keep it rebased on master.

**Comment by matty45** [comment]
ah

**Comment by danielga** [comment]
Can you remove the function instead please?

**Comment by matty45** [comment]
okay

**Comment by danielga** [comment]
Thanks.

**Review by danielga — APPROVED** [review]

**Pull request merged**
